name: cities-graphlets
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - anyio=3.3.0=py39h6e9494a_0
  - appnope=0.1.2=py39h6e9494a_1
  - argon2-cffi=20.1.0=py39h89e85a6_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.0.0=pyhd8ed1ab_0
  - boost-cpp=1.74.0=hff03dee_4
  - branca=0.4.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h89e85a6_1001
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.2=h0d85af4_0
  - ca-certificates=2020.10.14=0
  - cairo=1.16.0=he43a7df_1008
  - certifi=2021.5.30=py39h6e9494a_0
  - cffi=1.14.6=py39hb71fe58_0
  - cfitsio=3.470=h01dc385_7
  - chardet=4.0.0=py39h6e9494a_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_0
  - cryptography=3.4.7=py39ha2c9959_0
  - curl=7.78.0=hb861fe1_0
  - cycler=0.10.0=py_2
  - debugpy=1.4.1=py39h9fcab8e_0
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=he49afe7_0
  - fiona=1.8.20=py39h10412eb_1
  - folium=0.12.0=pyhd8ed1ab_1
  - fontconfig=2.13.1=h10f422b_1005
  - freetype=2.10.4=h4cff582_1
  - freexl=1.0.6=h0d85af4_0
  - gdal=3.3.1=py39h0530131_1
  - geopandas=0.9.0=pyhd8ed1ab_1
  - geopandas-base=0.9.0=pyhd8ed1ab_1
  - geos=3.9.1=he49afe7_2
  - geotiff=1.6.0=h26421ea_6
  - gettext=0.19.8.1=h7937167_1005
  - giflib=5.2.1=hbcb3906_2
  - hdf4=4.2.15=hefd3b78_3
  - hdf5=1.10.6=nompi_hc5d9132_1114
  - icu=68.1=h74dc148_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.6.4=py39h6e9494a_0
  - ipykernel=6.2.0=py39h71a6800_0
  - ipython=7.26.0=py39h71a6800_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h0d85af4_2003
  - jedi=0.18.0=py39h6e9494a_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=hbcb3906_0
  - json-c=0.15=hcb556a6_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39h6e9494a_0
  - jupyter_server=1.10.2=pyhd8ed1ab_0
  - jupyterlab=3.1.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.7.0=pyhd8ed1ab_0
  - kealib=1.4.14=h31dd65d_2
  - kiwisolver=1.3.1=py39hf018cea_1
  - krb5=1.19.2=hcfbf3a7_0
  - lcms2=2.12=h577c468_0
  - lerc=2.2.1=h046ec9c_0
  - libblas=3.9.0=11_osx64_openblas
  - libcblas=3.9.0=11_osx64_openblas
  - libcurl=7.78.0=hf45b732_0
  - libcxx=12.0.1=habf9029_0
  - libdap4=3.20.6=h3e144a0_2
  - libdeflate=1.7=h35c211d_5
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=h046ec9c_2
  - libgdal=3.3.1=hd51e85c_1
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.68.3=hd556434_0
  - libiconv=1.16=haf1e3a3_0
  - libkml=1.3.0=h8fd9edb_1014
  - liblapack=3.9.0=11_osx64_openblas
  - libnetcdf=4.8.0=nompi_hb4d10b0_103
  - libnghttp2=1.43.0=h07e645a_0
  - libopenblas=0.3.17=openmp_h3351f45_1
  - libpng=1.6.37=h7cec526_2
  - libpq=13.3=hea3049e_0
  - librttopo=1.1.0=h5413771_6
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=1.9.3=he49afe7_4
  - libspatialite=5.0.1=h035f608_5
  - libssh2=1.9.0=h52ee1ee_6
  - libtiff=4.3.0=h1167814_1
  - libwebp-base=1.2.1=h0d85af4_0
  - libxml2=2.9.12=h93ec3fd_0
  - libzip=1.8.0=h8b0c345_0
  - llvm-openmp=12.0.1=hda6cdc1_1
  - lz4-c=1.9.3=he49afe7_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h89e85a6_0
  - matplotlib-base=3.4.3=py39hb07454d_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py39h89e85a6_1004
  - munch=2.5.0=py_0
  - nbclassic=0.3.1=pyhd8ed1ab_1
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.1.0=py39h6e9494a_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - networkx=2.6.2=pyhd8ed1ab_0
  - notebook=6.4.3=pyha770c72_0
  - numpy=1.21.2=py39h7eed0ac_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1k=h0d85af4_1
  - osmnx=1.1.1=pyhd8ed1ab_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.2=py39h4d6be9b_0
  - pandoc=2.14.1=h0d85af4_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pcre=8.45=he49afe7_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py39he9bb72f_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - poppler=21.03.0=h640f9a4_0
  - poppler-data=0.4.10=0
  - postgresql=13.3=he8fe76e_0
  - proj=8.0.1=h1512c50_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=3.1.0=py39h7b8b08e_4
  - pyrsistent=0.17.3=py39h89e85a6_2
  - pysocks=1.7.1=py39h6e9494a_3
  - python=3.9.6=hd187cdc_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.2.1=py39h7fec2f1_0
  - rasterio=1.2.6=py39h906574e_2
  - readline=8.1=h05e3726_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-unixsocket=0.2.0=py_0
  - rtree=0.9.7=py39h7d0d40a_2
  - scikit-learn=0.24.2=py39hd4eea88_1
  - scipy=1.7.1=py39h056f1c0_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=57.4.0=py39h6e9494a_0
  - shapely=1.7.1=py39h1d9c377_5
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py39h6e9494a_1
  - snuggs=1.4.7=py_0
  - sqlite=3.36.0=h23a322b_0
  - statsmodels=0.12.2=py39h329c335_0
  - terminado=0.10.1=py39h6e9494a_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tiledb=2.3.3=h8370e7a_0
  - tk=8.6.10=h0419947_1
  - tornado=6.1=py39h89e85a6_1
  - tqdm=4.50.2=py_0
  - traitlets=5.0.5=py_0
  - tzcode=2021a=h0d85af4_2
  - tzdata=2021a=he74cb21_1
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py39h6e9494a_4
  - wheel=0.37.0=pyhd8ed1ab_1
  - xerces-c=3.2.3=h379762d_2
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.4=h1c7c35f_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.5.0=h582d3a0_0
